name: project_euler
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: chaucaocmg <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  #  path: ^1.4.1
  test: ^1.5.3
#dev_dependencies:

